version: '3.4'

services:   

  frontend:
    image: store:latest
    build:
        context: .
        dockerfile: ./eShopLite/Store/Dockerfile    
    environment: 
      - ProductEndpoint=http://backend:8080
      - ZIPKIN_URL=http://zipkin:9411
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=13b750a0-53b3-499e-9ef0-9eeabf571ec9;IngestionEndpoint=https://eastus-1.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/ 
    ports:
      - "32000:8080"
    depends_on: 
      - backend
      - prometheus
      - zipkin     

  backend:
    image: products:latest
    build: 
        context: .
        dockerfile: ./eShopLite/Products/Dockerfile    
    ports: 
      - "32001:8080"
    depends_on:
      - prometheus
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=13b750a0-53b3-499e-9ef0-9eeabf571ec9;IngestionEndpoint=https://eastus-1.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/           

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus/data      
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources   
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
